server:
  port: 8090  # 网关对外端口

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos 地址

    gateway:
      discovery:
        locator:
          enabled: true               # 开启服务发现路由（根据服务名自动路由）
          lower-case-service-id: true # 服务ID转小写

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        # 1. 新闻管理服务 (news-service)
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/api/admin/**, /api/news/upload

        # 2. 事件统计服务 (event-service)
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**, /api/emergency-events/**, /api/reported-incidents, /api/reported-incidents/** ,/api/reported-incidents-detail/**, /api/*-point

        # 3. 小程序后台服务 (miniprogram-service)
        - id: miniprogram-service
          uri: lb://miniprogram-service
          predicates:
            - Path=/api/user/login, /api/notice/reported/**, /api/myevents/**, /api/events/**, /api/common/upload

        # 4. 用户管理服务 (user-service)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/admin/**

        # 5. 物资管理服务 (material-service)
        - id: material-service
          uri: lb://material-service
          predicates:
            - Path=/api/materials, /api/materials/**, /api/category, /api/warehouses, /api/warehouses/**

        # 6. 鉴权与部门管理服务 (auth-service)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/admins, /api/admin/**, /api/admins/**, /api/admininfo, /api/admininfo/**, /api/avatar/upload, /api/worker/auth/workerLogin, /api/deptslist, /api/depts, /api/depts/**

        # 7. AI 决策服务/预案服务 (cbr-service)
        - id: cbr-service
          uri: lb://cbr-service
          predicates:
            - Path=/api/emergency-schemes, /api/emergency-schemes/**, /api//plan/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # 调试时开启，上线关闭
